### ISSUE TITLE
CORS issue

### ISSUE THREAD

**Issue by ghost** [nitsan-technologies/ns_instagram#16]
`Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://www.instagram.com/xxxxxxxx/. (Reason: CORS header 'Access-Control-Allow-Origin' missing).`

This has started popping up unfortunately.

**Comment by nitsan-technologies** [comment]
Hello @benabbottnz 

Thanks for the message. Please find the reason related to this issue here: https://github.com/nitsan-technologies/ns_instagram/issues/17#issuecomment-801812406

So, this is not an issue of this extension, But we will get back to you if we able to resolve this 

Thanks!
Team NITSAN
