### ISSUE TITLE
error 404

### ISSUE THREAD

**Issue by obifur** [nitsan-technologies/ns_instagram#7]
I use typo3 v6.2.25 with your plugin, but It just won't work (error 404):

The script tries to load:
"https://api.instagram.com/v1/users//media/recent?access_token=[...]&count=33&callback=jQuery224024281937368625905_1530218795955&_=1530218795956".

if I look at the instagram API, I think there is a "self" missing?? Like: 
https://api.instagram.com/v1/users/self/?access_token=ACCESS-TOKEN

https://github.com/nitsan-technologies/ns_instagram/blob/901d3d66b7679e570b164cccc46b92227def7492/Resources/Public/Feed/Js/instagram.js#L508

Excuse me if I'm completly wrong - I'm not an expert :)

**Comment by nitsan-technologies** [comment]
Hello @obifur 

We have made some changes according to latest Instagram API at this repository.
So, please download latest changes from this repository and share your thought for the same.
Let us know if you still get any error.
**Download link** = https://github.com/nitsan-technologies/ns_instagram

Have a great day ahead :)

Thanks!

**Comment by obifur** [comment]
Sorry, i forgot to mention that I'm using ns_instagram v. 1.0.0
I don't see a newer one - did I miss something?

**Comment by nitsan-technologies** [comment]
Hey @obifur 

**Problem:**
Actually, Instagram has made some changes in his API. That's why this kind of issue is accruing in extension. At TER there is still we have not updated this extension. We are working on it according to the latest Instagram API changes at git repository. 

**Quick Solution:**
So, we prefer that download this extension from this git repository we have updated code at this repository. So use it and let us know if still, this issue occurs.
URL: https://github.com/nitsan-technologies/ns_instagram

You can keep watch & feel free to write any other issues or suggestions.

Thank you very much for your time :)

**Comment by obifur** [comment]
Ok. After some trail and error I managed to install the newest version of this extension. I learned that the zip-file must not contain a subfolder and the name is importatnt ;) 

Although the version still states 1.0.0, it's working now perfectly! Thank you very much!
